#!/bin/bash
# =============================================================================
# scripts/system/detect-hw.sh — Dynamic Hardware & VM Environment Detector
# =============================================================================
# Detects: VirtualBox/VMs, NVIDIA hardware, or Intel/AMD hardware.
# Supports: manual overrides via command-line arguments.
# Generates: ~/.config/hypr/hw-env.conf for Hyprland to source.
# =============================================================================

ENV_FILE="${HOME}/.config/hypr/hw-env.conf"

# Ensure the config directory exists
mkdir -p "$(dirname "$ENV_FILE")"

# Reset the override file
cat << 'EOF' > "$ENV_FILE"
# =============================================================================
# hw-env.conf — Dynamically generated hardware environment variables
# =============================================================================
# Automatically generated by detect-hw.sh. DO NOT EDIT DIRECTLY.
# =============================================================================
EOF

# Helper functions
info() { echo -e "\033[0;32m[✓]\033[0m $*"; }

write_vm() {
    info "Applying VM rendering overrides..."
    cat << 'EOF' >> "$ENV_FILE"
# Virtual Machine Overrides (VirtualBox/QEMU)
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_RENDERER_ALLOW_SOFTWARE,1
EOF
}

write_nvidia() {
    info "Applying proprietary Nvidia driver overrides..."
    cat << 'EOF' >> "$ENV_FILE"
# NVIDIA GPU Overrides
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = NVD_BACKEND,direct
EOF
}

write_intel_amd() {
    info "Using native open-source drivers (Intel/AMD)..."
    cat << 'EOF' >> "$ENV_FILE"
# Intel/AMD Real Hardware Settings
# Native hardware cursors enabled, no Nvidia/VM workarounds needed.
EOF
}

# Parse arguments
MODE="auto"
for arg in "$@"; do
    case "$arg" in
        --nvidia|-n)                    MODE="nvidia" ;;
        --vm|-v)                        MODE="vm" ;;
        --intel-amd|--intel|--amd|-i)   MODE="intel-amd" ;;
        --auto|-a)                      MODE="auto" ;;
        --help|-h)
            echo "Usage: detect-hw.sh [--nvidia | --vm | --intel-amd | --auto]"
            exit 0
            ;;
    esac
done

if [ "$MODE" = "vm" ]; then
    info "Forcing hardware mode: VM (VirtualBox/QEMU)"
    write_vm
elif [ "$MODE" = "nvidia" ]; then
    info "Forcing hardware mode: NVIDIA proprietary"
    write_nvidia
elif [ "$MODE" = "intel-amd" ]; then
    info "Forcing hardware mode: Intel/AMD open-source"
    write_intel_amd
else
    # Auto-detect mode
    # 1. Detect Virtualization (VirtualBox, QEMU, VMware, etc.)
    IS_VM=false
    if command -v systemd-detect-virt &>/dev/null; then
        if systemd-detect-virt -q; then
            IS_VM=true
            VM_TYPE=$(systemd-detect-virt)
        fi
    elif grep -iqE '(virtualbox|qemu|kvm|vmware|hyper-v)' /proc/cpuinfo /proc/version 2>/dev/null; then
        IS_VM=true
        VM_TYPE="detected-from-proc"
    fi

    if [ "$IS_VM" = true ]; then
        info "Auto-detected: Virtual Machine (${VM_TYPE:-unknown})"
        write_vm
    # 2. Detect NVIDIA GPU
    elif lspci 2>/dev/null | grep -qi 'nvidia'; then
        info "Auto-detected: NVIDIA GPU"
        write_nvidia
    # 3. Default: Intel / AMD
    else
        info "Auto-detected: Intel/AMD Real Hardware"
        write_intel_amd
    fi
fi
